# Generated by Django 4.0.4 on 2023-07-19 10:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flight_service', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='crew',
            name='first_name',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='crew',
            name='last_name',
            field=models.CharField(max_length=255),
        ),
    ]
