# Generated by Django 4.0.4 on 2023-07-20 10:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flight_service', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='flight',
            name='crew',
            field=models.ManyToManyField(blank=True, null=True, to='flight_service.crew'),
        ),
    ]
