# Generated by Django 4.0.4 on 2023-07-21 06:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Airport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('icao', models.TextField(blank=True, null=True)),
                ('iata', models.TextField(blank=True, null=True)),
                ('name', models.CharField(max_length=255)),
                ('city', models.TextField(blank=True, null=True)),
                ('state', models.TextField(blank=True, null=True)),
                ('country', models.TextField(blank=True, null=True)),
                ('elevation', models.IntegerField(blank=True, null=True)),
                ('lat', models.DecimalField(blank=True, decimal_places=15, max_digits=20, null=True)),
                ('lon', models.DecimalField(blank=True, decimal_places=15, max_digits=20, null=True)),
                ('tz', models.TextField(blank=True, null=True)),
                ('lid', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Route',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('distance', models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True)),
                ('destination', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='destination_routes', to='route_service.airport')),
                ('source', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='source_routes', to='route_service.airport')),
            ],
        ),
    ]
