# Generated by Django 4.0.4 on 2023-07-20 06:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Airport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('icao', models.TextField()),
                ('iata', models.TextField()),
                ('name', models.CharField(max_length=255, unique=True)),
                ('city', models.TextField()),
                ('state', models.TextField()),
                ('country', models.TextField()),
                ('elevation', models.IntegerField()),
                ('lat', models.DecimalField(decimal_places=10, max_digits=14)),
                ('lon', models.DecimalField(decimal_places=10, max_digits=14)),
                ('tz', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Route',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('distance', models.IntegerField()),
                ('destination', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='destination_routes', to='route_service.airport')),
                ('source', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='source_routes', to='route_service.airport')),
            ],
        ),
    ]
