# Generated by Django 4.0.4 on 2023-07-20 07:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('route_service', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='airport',
            name='lid',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='airport',
            name='city',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='airport',
            name='country',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='airport',
            name='elevation',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='airport',
            name='iata',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='airport',
            name='icao',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='airport',
            name='lat',
            field=models.DecimalField(decimal_places=80, max_digits=100),
        ),
        migrations.AlterField(
            model_name='airport',
            name='lon',
            field=models.DecimalField(decimal_places=80, max_digits=100),
        ),
        migrations.AlterField(
            model_name='airport',
            name='state',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='airport',
            name='tz',
            field=models.TextField(blank=True, null=True),
        ),
    ]
