# Generated by Django 4.0.4 on 2023-07-20 07:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('route_service', '0002_airport_lid_alter_airport_city_alter_airport_country_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='airport',
            name='lat',
            field=models.DecimalField(decimal_places=15, max_digits=20),
        ),
        migrations.AlterField(
            model_name='airport',
            name='lon',
            field=models.DecimalField(decimal_places=15, max_digits=20),
        ),
        migrations.AlterField(
            model_name='airport',
            name='name',
            field=models.CharField(max_length=255),
        ),
    ]
